#pragma once

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 400

#define CELL_WIDTH 25
#define ROWS (WINDOW_HEIGHT / CELL_WIDTH)
#define COLS (WINDOW_WIDTH / CELL_WIDTH)

#define GRID_SIZE ROWS * COLS

